spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: ture
        default_batch_fetch_size: 100
    open-in-view: false

  servlet:
    multipart:
      enabled: true
      max-request-size: 30MB
      max-file-size: 10MB

damoa:
  file:
    image:
      upload:
        path: uploads

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: traces