cloud:
  aws:
    credentials:
      accessKey: AKIAQDKER7QLVDB2C3H3
      secretKey: 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
    s3:
      bucket: damoabucket
      baseuri: https://damoabucket.s3.ap-northeast-2.amazonaws.com/
    region:
      static: ap-northeast-2
    stack:
      auto: false
