spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2-data/sns
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

  servlet:
    multipart:
      enabled: true
      max-request-size: 30MB
      max-file-size: 10MB

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

app:
  jwtSecret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2ImlsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  jwtExpirationInMs: 604800000

sns:
  upload:
    path: /Users/kimjiwon/studyProject/sns/uploads