ifndef::snippets[]
:snippets: ../../../build/generated-snippets
endif::[]
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:
:operation-http-request-title: Request
:operation-http-response-title: Response

[[resources]]
= DAMOA-API GUIDE

[[resources-members]]
== 사용자(Members) API

[[resources-members-create]]

=== 회원 가입

`POST` 요청으로 회원가입을 할 수 있다.

operation::create-members[snippets='http-request,http-response,request-headers,request-fields,response-headers,response-fields']

[[resources-members-email-check]]

=== 이메일 중복체크

`GET` 요청으로 이메일 중복체크를 할 수 있다.

operation::check-email[snippets='http-request,http-response,path-parameters']

[[resources-members-loin]]

=== 로그인

`POST` 요청으로 로그인할 수 있다.

operation::login-members[snippets='http-request,http-response,request-headers,request-fields,response-headers,response-fields']

[[resources-members-get]]

=== 사용자 정보 조회

`GET` 요청으로 사용자 정보 조회를 할 수 있다.

operation::get-members[snippets='http-request,http-response,request-headers,response-headers,response-fields']

[[resources-members-update]]

=== 사용자 정보 업데이트

`PATCH` 요청으로 사용자 정보를 업데이트할 수 있다.

operation::update-members[snippets='http-request,http-response,request-headers,request-fields,response-headers,response-fields']

[[resources-members-change-profile]]

=== 사용자 프로필 사진 변경

`POST` 요청으로 현재 사용자의 프로필 사진을 바꿀수 있다.

operation::change-profile-image[snippets='http-request,http-response,request-headers,request-parts,response-headers,response-fields']

[[resources-members-communities-get]]

=== 사용자가 가입한 커뮤니티 정보 조회

`GET` 요청으로 사용자가 가입한 커뮤니티 정보를 조회할 수 있다.

operation::get-joined-communities[snippets='http-request,http-response,request-parameters,request-headers,response-headers,response-fields']

[[resources-communities]]
== 커뮤니티(Communities) API

[[resources-communities-create]]

=== 커뮤니티 생성

`POST` 요청으로 커뮤니티를 생성할 수 있다.

operation::create-communities[snippets='http-request,http-response,request-headers,request-parameters,request-parts,response-headers,response-fields']

[[resources-communities-email-check]]

=== 커뮤니티 이름 중복체크

`GET` 요청으로 커뮤니티 이름 중복체크를 할 수 있다.

operation::check-name[snippets='http-request,http-response,request-headers,path-parameters']

[[resources-communities-join]]

=== 커뮤니티 가입

`POST` 요청으로 커뮤니티에 가입할 수 있다.

operation::join-communities[snippets='http-request,http-response,request-headers,path-parameters']


[[resources-communities-withdraw]]

=== 커뮤니티 탈퇴

`POST` 요청으로 커뮤니티를 탈퇴할 수 있다.

operation::withdraw-communities[snippets='http-request,http-response,request-headers,path-parameters']


[[resources-communities-update]]

=== 커뮤니티 수정

`POST` 요청으로 커뮤니티를 수정할 수 있다.

operation::update-communities[snippets='http-request,http-response,request-headers,path-parameters,request-parameters,request-parts,response-headers,response-fields']


[[resources-communities-get]]

=== 커뮤니티 조회

`GET` 요청으로 커뮤니티를 조회할 수 있다.

operation::get-communities[snippets='http-request,http-response,request-headers,path-parameters,response-headers,response-fields']


[[resources-communities-query]]

=== 모든 커뮤니티 정보 조회(검색)

`GET` 요청으로 모든 커뮤니티를 조회할 수 있다.

operation::query-communities[snippets='http-request,http-response,request-parameters,request-headers,response-headers,response-fields']


[[resources-communities-members-query]]

=== 모든 커뮤니티 사용자 조회

`GET` 요청으로 모든 커뮤니티 사용자을 조회할 수 있다.

operation::query-communities-member[snippets='http-request,http-response,path-parameters,request-parameters,request-headers,response-headers,response-fields']

[[resources-posts]]
== 게시글(Posts) API

[[resources-posts-create]]
=== 게시글 작성

`POST` 요청으로 게시글을 작성할 수 있다.

operation::create-posts[snippets='http-request,http-response,request-headers,path-parameters,request-parameters,request-parts,response-headers,response-fields']
