= DAMOA REST API Guide
김지원;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:
:operation-http-request-title: Request
:operation-http-response-title: Response

[[overview]]
= 개요

[[overview-http-verbs]]
== HTTP 동사

본 REST API에서 사용하는 HTTP 동사(verbs)는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 동사 | 용례

| `GET`
| 리소스를 가져올 때 사용

| `POST`
| 새 리소스를 만들 때 사용

| `PUT`
| 기존 리소스를 수정할 때 사용

| `PATCH`
| 기존 리소스의 일부를 수정할 때 사용

| `DELETE`
| 기존 리소스를 삭제할 떄 사용
|===

[[overview-http-status-codes]]
== HTTP 상태 코드

본 REST API에서 사용하는 HTTP 상태 코드는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 상태 코드 | 용례

| `200 OK`
| 요청을 성공적으로 처리함

| `201 Created`
| 새 리소스를 성공적으로 생성함. 응답의 `Location` 헤더에 해당 리소스의 URI가 담겨있다.

| `204 No Content`
| 기존 리소스를 성공적으로 수행하거나 삭제함. 응답 본문이 없다.

| `400 Bad Request`
| 잘못된 요청을 보낸 경우. 응답 본문에 더 오류에 대한 정보가 담겨있다.

| `401 Unauthorized`
| 인증을 하지 않고 리소스에 접근한 경우. 주로 로그인과 관련 있다.

| `403 Forbidden`
| 인증은 하였으나 해당 리소스에 접근 권한이 없을 경우

| `404 Not Found`
| 요청한 리소스가 없는 경우.

| `405 Method Not Allowed`
| 허용하지 않는 HTTP Method로 접근한 경우
|===

[[resources]]
= 리소스

[[resources-members]]
== 사용자(Members) API

[[resources-members-create]]
=== 회원 가입

`POST` 요청으로 회원가입을 할 수 있다.

operation::create-members[snippets='http-request,http-response,request-headers,request-fields,response-headers,response-fields']

[[resources-members-email-check]]
=== 이메일 중복체크

`GET` 요청으로 이메일 중복체크를 할 수 있다.

operation::check-email[snippets='http-request,http-response,path-parameters']

[[resources-members-loin]]
=== 로그인

`POST` 요청으로 로그인할 수 있다.

operation::login-members[snippets='http-request,http-response,request-headers,request-fields,response-headers,response-fields']

[[resources-members-get]]
=== 사용자 정보 조회

`GET` 요청으로 사용자 정보 조회를 할 수 있다.

operation::get-members[snippets='http-request,http-response,request-headers,response-headers,response-fields']

[[resources-members-update]]
=== 사용자 정보 업데이트

`PATCH` 요청으로 사용자 정보를 업데이트할 수 있다.

operation::update-members[snippets='http-request,http-response,request-headers,request-fields,response-headers,response-fields']

[[resources-members-change-profile]]
=== 사용자 프로필 사진 변경

`POST` 요청으로 현재 사용자의 프로필 사진을 바꿀수 있다.

operation::change-profile-image[snippets='http-request,http-response,request-headers,request-parts,response-headers,response-fields']

[[resources-members-communities-get]]
=== 사용자가 가입한 커뮤니티 정보 조회

`GET` 요청으로 사용자가 가입한 커뮤니티 정보를 조회할 수 있다.

operation::query-joined-communities[snippets='http-request,http-response,request-headers,request-parameters,response-headers,response-fields']

[[resources-members-posts-get]]
=== 사용자가 가입한 모든 커뮤니티의 모든 게시글 조회(Feeds)

`GET` 요청으로 사용자가 가입한 모든 커뮤니티의 모든 게시글을 조회할 수 있다.

operation::query-members-posts[snippets='http-request,http-response,request-headers,request-parameters,response-headers,response-fields']


[[resources-communities]]
== 커뮤니티(Communities) API

[[resources-communities-create]]
=== 커뮤니티 생성

`POST` 요청으로 커뮤니티를 생성할 수 있다.

operation::create-communities[snippets='http-request,http-response,request-headers,request-parameters,request-parts,response-headers,response-fields']

[[resources-communities-email-check]]
=== 커뮤니티 이름 중복체크

`GET` 요청으로 커뮤니티 이름 중복체크를 할 수 있다.

operation::check-name[snippets='http-request,http-response,request-headers,path-parameters']

[[resources-communities-get]]
=== 커뮤니티 단건 조회

`GET` 요청으로 커뮤니티를 단건 조회할 수 있다.

operation::get-communities[snippets='http-request,http-response,request-headers,path-parameters,response-headers,response-fields']

[[resources-communities-query]]
=== 모든 커뮤니티 정보 조회(검색)

`GET` 요청으로 모든 커뮤니티를 조회할 수 있다.

operation::query-communities[snippets='http-request,http-response,request-headers,request-parameters,response-headers,response-fields']

[[resources-communities-update]]
=== 커뮤니티 수정

`POST` 요청으로 커뮤니티를 수정할 수 있다.

operation::update-communities[snippets='http-request,http-response,request-headers,path-parameters,request-parameters,request-parts,response-headers,response-fields']

[[resources-communities-join]]
=== 커뮤니티 가입

`POST` 요청으로 커뮤니티에 가입할 수 있다.

operation::join-communities[snippets='http-request,http-response,request-headers,path-parameters']

[[resources-communities-withdraw]]
=== 커뮤니티 탈퇴

`POST` 요청으로 커뮤니티를 탈퇴할 수 있다.

operation::withdraw-communities[snippets='http-request,http-response,request-headers,path-parameters']

[[resources-communities-members-query]]
=== 커뮤니티 모든 사용자 조회

`GET` 요청으로 커뮤니티의 모든 사용자을 조회할 수 있다.

operation::query-communities-member[snippets='http-request,http-response,request-headers,path-parameters,request-parameters,response-headers,response-fields']


[[resources-posts]]
== 게시글(Posts) API

[[resources-posts-create]]
=== 게시글 작성

`POST` 요청으로 게시글을 작성할 수 있다.

operation::create-posts[snippets='http-request,http-response,request-headers,path-parameters,request-parameters,request-parts,response-headers,response-fields']

[[resources-posts-get]]
=== 게시글 단건 조회

`GET` 요청으로 게시글을 단건 조회할 수 있다.

operation::get-posts[snippets='http-request,http-response,request-headers,path-parameters,response-headers,response-fields']

[[resources-posts-query]]
=== 커뮤니티의 모든 게시글 조회

`GET` 요청으로 커뮤니티의 모든 게시글을 조회할 수 있다.

operation::query-posts[snippets='http-request,http-response,request-headers,path-parameters,request-parameters,response-headers,response-fields']

[[resources-posts-delete]]
=== 게시글 삭제

`DELETE` 요청으로 게시글을 삭제할 수 있다.

operation::delete-posts[snippets='http-request,http-response,request-headers,path-parameters']


[[resources-comments]]
== 댓글(Comments) API

[[resources-comments-create]]
=== 댓글 작성

`POST` 요청으로 댓글을 작성할 수 있다.

operation::create-comments[snippets='http-request,http-response,request-headers,path-parameters,request-fields,response-headers,response-fields']

[[resources-comments-get]]
=== 댓글 단건 조회

`GET` 요청으로 댓글을 단건 조회할 수 있다.

operation::get-comments[snippets='http-request,http-response,request-headers,path-parameters,response-headers,response-fields']

[[resources-comments-query]]
=== 댓글 복수건 조회

`GET` 요청으로 댓글을 복수건 조회할 수있다. +
단, 부모 댓글만 조회하고, 부모댓글에 연관된 자식 댓글의 수를 표시한다.

operation::query-parent-comments[snippets='http-request,http-response,request-headers,path-parameters,request-parameters,response-headers,response-fields']

[[resources-comments-delete]]
=== 댓글 삭제

`DELETE` 요청으로 댓글을 작성할 수 있다. +
부모 댓글을 삭제하면 자식 댓글까지 삭제 된다.

operation::delete-comments[snippets='http-request,http-response,request-headers,path-parameters']

[[resources-comments-update]]
=== 댓글 수정

`PATCH` 요청으로 댓글을 수정할 수 있다.

operation::update-comments[snippets='http-request,http-response,request-headers,path-parameters,request-fields,response-headers,response-fields']
